### ISSUE TITLE
How to use Kuromoji in Gradle?

### ISSUE THREAD

**Issue by weituotian** [atilika/kuromoji#120]
```
   // https://mvnrepository.com/artifact/org.atilika.kuromoji/kuromoji
    compile group: 'org.atilika.kuromoji', name: 'kuromoji', version: '0.9.0'
```

and it will cause an error!

```
Error:Failed to resolve: org.atilika.kuromoji:kuromoji:0.9.0
```

**Comment by cmoen** [comment]
Could you try `com.atilika.kuromoji: kuromoji-ipadic:0.9.0` and see how that goes?  Thanks.

**Comment by weituotian** [comment]
![q -20171005101703](https://user-images.githubusercontent.com/7270968/31208293-6a485dd8-a9b6-11e7-95ce-bce66ca5754f.png)

@cmoen it get the same error!

![q -20171005101749](https://user-images.githubusercontent.com/7270968/31208307-7a82459c-a9b6-11e7-8974-3f2350576c66.png)

**Comment by take-iwiw** [comment]
I just faced a similar issue.
The following build.gradle worked to me. "pickFirst" is kind of workaround and there should be the better way.

```
android {
    packagingOptions {
        pickFirst 'META-INF/CONTRIBUTORS.md'
        pickFirst 'META-INF/LICENSE.md'
    }
}

dependencies {
    // https://mvnrepository.com/artifact/com.atilika.kuromoji/kuromoji-ipadic
    compile group: 'com.atilika.kuromoji', name: 'kuromoji-ipadic', version: '0.9.0'

}
```

**Comment by weituotian** [comment]
@cmoen @take-iwiw 
your solution is very excellent! it had solved this problem!thanks so much!
