### ISSUE TITLE
Obtain furigana?

### ISSUE THREAD

**Issue by Mr-SD** [atilika/kuromoji#121]
Hi, the documentation says kuromoji can extract the readings for kanji and shows an example in which the reading for each token is extracted. However, is it possible to extract what part of the reading corresponds to each kanji?

For example, given a token with the contents:

    "寿司" -> 寿 = ス, 司 = シ

**Comment by cmoen** [comment]
Kuromoji provides reading information at the token/morpheme level.  Reading for each kanji can be inferred by using per-kanji readings found in kanji dictionaries, such as kanjidic2 (http://www.edrdg.org/kanjidic/kanjd2index.html) which is freely available.
