### ISSUE TITLE
Nexus Repository is Offline?

### ISSUE THREAD

**Issue by ryantenney** [atilika/kuromoji#123]
All requests to http://www.atilika.org/nexus/content/repositories/atilika are 404-ing.

**Comment by cmoen** [comment]
I strongly recommend getting your artifacts from Maven Central instead.  Use:

```
<dependency>
  <groupId>com.atilika.kuromoji</groupId>
  <artifactId>kuromoji-ipadic</artifactId>
  <version>0.9.0</version>
</dependency>
```

If you were on version 0.7.7, I also strongly recommend upgrading to this version.  I believe the code changes necessary would only be to add `ipadic` to your package path.
