### ISSUE TITLE
Very odd tokenization of a sentence

### ISSUE THREAD

**Issue by kallewoof** [atilika/kuromoji#82]
Tokenizing "色々やらなきゃならんことがたくさんあるんだ" in the command line version of Kuromoji (using ipadic) results in 

色々
やら
なき
ゃならんことがたくさんあるんだ

The same output is observed in the online demo available at http://www.atilika.org/

**Comment by kallewoof** [comment]
Tried unidic-neologd dictionary, and it parses the token fine. I guess ipadic is a bit volatile..?

**Comment by cmoen** [comment]
This isn't really a bug, but rather a limitation of IPADIC to deal with colloquial language. Try a UniDic-variant if you need to analyze colloquial language.
